{% set name = "wagtail-charcount" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wagtail-charcount-{{ version }}.tar.gz
  sha256: 3bfdc258e4f6a3962a5c69cd0231c848a22180012477d38ba48ec47b52488829

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - wagtail >=4.1

test:
  imports:
    - wagtailcharcount
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/takeflight/wagtail-charcount
  summary: A wagtail character and word counting plugin for RichTextFields.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
